# Generated by Django 5.2.8 on 2026-01-22 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Auto-generated from first message if empty', max_length=255, verbose_name='Title')),
                ('model_used', models.CharField(default='llama3', help_text='Model key used (llama3, mistral, qwen)', max_length=50, verbose_name='AI Model')),
                ('enable_history', models.BooleanField(default=True, help_text='If False, each message is processed without context', verbose_name='Enable History')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_conversations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(default='llama3', help_text='Model used for new conversations', max_length=50, verbose_name='Default Model')),
                ('default_enable_history', models.BooleanField(default=True, verbose_name='Enable History by Default')),
                ('max_context_messages', models.IntegerField(default=10, help_text='Number of messages included in context', verbose_name='Max Context Messages')),
                ('temperature', models.FloatField(default=0.7, help_text='Response creativity (0.0-1.0)', verbose_name='Temperature')),
                ('max_tokens', models.IntegerField(default=512, help_text='Maximum response length', verbose_name='Max Tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ia_chat_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Conversation Preference',
                'verbose_name_plural': 'Conversation Preferences',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System')], max_length=10, verbose_name='Role')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens generated (assistant only)', null=True, verbose_name='Tokens Used')),
                ('generation_time', models.FloatField(blank=True, help_text='Duration in seconds (assistant only)', null=True, verbose_name='Generation Time (s)')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ia_chat.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='ia_chat_con_updated_b60b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-created_at'], name='ia_chat_con_user_id_cb8444_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='ia_chat_mes_convers_54a61e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='ia_chat_mes_role_3d129f_idx'),
        ),
    ]
