# Generated by Django 5.2.8 on 2026-01-18 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenu du commentaire', max_length=1000)),
                ('is_approved', models.BooleanField(default=True, help_text='Commentaire approuvé par un modérateur')),
                ('is_edited', models.BooleanField(default=False, help_text='Commentaire modifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Pour les réponses aux commentaires', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='article.comment')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='article_com_created_7a40aa_idx'), models.Index(fields=['article', '-created_at'], name='article_com_article_868c68_idx')],
            },
        ),
    ]
