# Generated by Django 5.2.8 on 2025-11-23 18:00

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='bio')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('role', models.CharField(choices=[('developer', 'Développeur'), ('student', 'Étudiant'), ('designer', 'Designer'), ('entrepreneur', 'Entrepreneur'), ('researcher', 'Chercheur'), ('other', 'Autre')], default='developer', max_length=20, verbose_name='role')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_premium', models.BooleanField(default=False, verbose_name='premium')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='avatar')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%d/', verbose_name='cover image')),
                ('reputation', models.IntegerField(default=0, verbose_name='reputation')),
                ('posts_count', models.IntegerField(default=0, verbose_name='posts count')),
                ('comments_count', models.IntegerField(default=0, verbose_name='comments count')),
                ('github', models.URLField(blank=True, verbose_name='github')),
                ('linkedin', models.URLField(blank=True, verbose_name='linkedin')),
                ('twitter', models.URLField(blank=True, verbose_name='twitter')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='email notifications')),
                ('newsletter', models.BooleanField(default=True, verbose_name='newsletter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
